spring:
  application:
    name: EmailNotificationMicroservice

  kafka:
    bootstrap-servers: localhost:9092  # optional global default

    consumer:
      bootstrap-servers: localhost:9092
#      group-id: product-created-events
      properties:
        spring.json.trusted.packages: com.app.core
      # Optional but useful for local testing:
      # auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

server:
  port: 0

consumer:
  group-id: product-created-events
